---
# tasks file for docker_install
#
- name: Mise à jour du cache APT
  apt:
    update-cache: yes

- name: Installation des paquets nécéssaires
  apt:
    name:
      - ca-certificates
      - curl
    state: present

- name: Ajout des permissions aux dossiers APT et de la clé gpg du répo docker
  shell: |
    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
    chmod a+r /etc/apt/keyrings/docker.asc

- name: Ajout du répo docker aux sources APT
  shell: |
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

- name: Mise à jour du cache APT
  apt:
    update-cache: yes

- name: Installation de docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
      - docker-compose

- name: téléchargement de l'image docker hello-world
  docker_image:
    name: hello-world
    source: pull
    pull:
      platform: amd64

- name: Run du docker hello-world
  docker_container:
    name: hello-world
    image: hello-world
    state: started